"""Build data/manifest.json + per-clip embedding JSON files.

This is the final step of the offline pipeline. It assembles the catalog
that the FastAPI backend serves at /api/library and writes one
per-clip embedding payload under data/embeddings/<id>.json.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Iterable

import numpy as np

from common import (
    CATEGORIES_PATH,
    EMBEDDINGS_DIR,
    DEFAULT_FEATURE_AXES,
    MANIFEST_PATH,
    SCALAR_FEATURES,
)
from extract_features import ClipFeatures
from compute_embeddings import normalize01


VERSION = "0.1.0"


# --------------------------------------------------------------------------- #
# Categories metadata (bilingual)
# --------------------------------------------------------------------------- #


DEFAULT_CATEGORIES: list[dict] = [
    {
        "id": "synthetic",
        "name_en": "Synthetic",
        "name_es": "Sintéticos",
        "description_en": "Algorithmically generated calibration sounds",
        "description_es": "Sonidos de calibración generados por algoritmo",
        "icon": "WAVE",
    },
    {
        "id": "birds",
        "name_en": "Birds",
        "name_es": "Aves",
        "description_en": "Bird songs and calls",
        "description_es": "Cantos y llamados de aves",
        "icon": "BIRD",
    },
    {
        "id": "mammals",
        "name_en": "Mammals",
        "name_es": "Mamíferos",
        "description_en": "Calls and vocalisations of mammals",
        "description_es": "Llamados y vocalizaciones de mamíferos",
        "icon": "PAW",
    },
    {
        "id": "amphibians_reptiles",
        "name_en": "Amphibians and reptiles",
        "name_es": "Anfibios y reptiles",
        "description_en": "Frogs, toads, and reptile vocalisations",
        "description_es": "Vocalizaciones de ranas, sapos y reptiles",
        "icon": "FROG",
    },
    {
        "id": "insects",
        "name_en": "Insects",
        "name_es": "Insectos",
        "description_en": "Stridulations and insect calls",
        "description_es": "Estridulaciones y llamados de insectos",
        "icon": "BUG",
    },
    {
        "id": "nature",
        "name_en": "Nature ambience",
        "name_es": "Ambientes naturales",
        "description_en": "Rain, wind, water, fire and other ambiences",
        "description_es": "Lluvia, viento, agua, fuego y otros ambientes",
        "icon": "LEAF",
    },
    {
        "id": "speeches",
        "name_en": "Famous speeches",
        "name_es": "Discursos famosos",
        "description_en": "Public-domain historical speeches",
        "description_es": "Discursos históricos en dominio público",
        "icon": "SPEAK",
    },
    {
        "id": "music",
        "name_en": "Music",
        "name_es": "Música",
        "description_en": "Public-domain or CC-licensed musical pieces",
        "description_es": "Obras musicales en dominio público o con licencia CC",
        "icon": "MUSIC",
    },
    {
        "id": "space",
        "name_en": "Space",
        "name_es": "Espacio",
        "description_en": "NASA recordings and space-related public-domain audio",
        "description_es": "Grabaciones de NASA y audio espacial en dominio público",
        "icon": "STAR",
    },
    {
        "id": "mechanical",
        "name_en": "Mechanical",
        "name_es": "Mecánicos",
        "description_en": "Machines, engines, vehicles, industrial sounds",
        "description_es": "Máquinas, motores, vehículos, sonidos industriales",
        "icon": "GEAR",
    },
]


def load_categories() -> list[dict]:
    if CATEGORIES_PATH.is_file():
        with CATEGORIES_PATH.open("r", encoding="utf-8") as fh:
            return json.load(fh)
    return DEFAULT_CATEGORIES


# --------------------------------------------------------------------------- #
# Catalog metadata per clip (titles, license)
# --------------------------------------------------------------------------- #


def derive_clip_metadata(features: ClipFeatures) -> dict:
    """Return catalog metadata for a clip.

    Looks up an optional sidecar JSON next to the audio file
    (``<clip>.meta.json``). If absent, derives sensible defaults from the
    file name and category.
    """
    sidecar = features.audio_path.with_suffix(".meta.json")
    if sidecar.is_file():
        with sidecar.open("r", encoding="utf-8") as fh:
            return json.load(fh)

    # Default: humanise the stem
    stem = features.audio_path.stem.replace("_", " ").replace("-", " ").strip()
    title = stem[:1].upper() + stem[1:]
    if features.category == "synthetic":
        return {
            "title_en": title,
            "title_es": title,
            "source": "Synthetic (generated by data-pipeline/synthetic_seeds.py)",
            "license": "CC0-1.0",
            "attribution": "Auralis project (public domain)",
            "tags": ["synthetic", "calibration"],
        }
    return {
        "title_en": title,
        "title_es": title,
        "source": "User-provided",
        "license": "Unknown",
        "attribution": "",
        "tags": [],
    }


# --------------------------------------------------------------------------- #
# Manifest + per-clip embeddings
# --------------------------------------------------------------------------- #


def write_clip_embedding(
    features: ClipFeatures,
    projections: dict[str, np.ndarray],
) -> Path:
    """Write the full embedding payload for a single clip."""
    EMBEDDINGS_DIR.mkdir(parents=True, exist_ok=True)
    target = EMBEDDINGS_DIR / f"{features.clip_id}.json"

    # 'features' track: pick six default axes.
    feat_matrix = np.column_stack(
        [features.scalar_features[name] for name in DEFAULT_FEATURE_AXES]
    )
    feat_matrix = normalize01(feat_matrix)

    tracks = [
        {
            "name": "features",
            "description_en": "Six interpretable spectral features per frame",
            "description_es": "Seis características espectrales interpretables por cuadro",
            "dim_labels": list(DEFAULT_FEATURE_AXES),
            "values": feat_matrix.round(4).tolist(),
        }
    ]
    for method, matrix in projections.items():
        if method == "yamnet":
            desc_en = "6D PCA projection of YAMNet's pretrained 1024-D embeddings (deep CNN trained on AudioSet)"
            desc_es = "Proyección PCA 6D de los embeddings preentrenados YAMNet de 1024-D (CNN profunda entrenada con AudioSet)"
        else:
            desc_en = f"6-dimensional {method.upper()} projection of MFCC frames"
            desc_es = f"Proyección {method.upper()} de 6 dimensiones de los cuadros MFCC"
        tracks.append(
            {
                "name": method,
                "description_en": desc_en,
                "description_es": desc_es,
                "dim_labels": [f"D{i + 1}" for i in range(matrix.shape[1])],
                "values": matrix.round(4).tolist(),
            }
        )

    raw = {
        "rms": features.scalar_features["rms"].round(5).tolist(),
        "spectral_centroid_hz": features.scalar_features["spectral_centroid"]
        .round(2)
        .tolist(),
        "dominant_pitch_hz": features.scalar_features["dominant_pitch"]
        .round(2)
        .tolist(),
    }

    payload = {
        "id": features.clip_id,
        "duration_seconds": round(features.duration_seconds, 3),
        "sample_rate": features.sample_rate,
        "hop_seconds": features.hop_seconds,
        "num_frames": features.num_frames,
        "tracks": tracks,
        "raw": raw,
    }
    with target.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, separators=(",", ":"))
    return target


def write_manifest(
    feature_set: Iterable[ClipFeatures],
    method_names: list[str],
) -> Path:
    """Assemble and persist the top-level catalog."""
    feature_set = list(feature_set)
    categories = load_categories()
    used_categories = {f.category for f in feature_set}
    categories_in_use = [c for c in categories if c["id"] in used_categories]

    clips = []
    for f in feature_set:
        meta = derive_clip_metadata(f)
        rel_audio = f.audio_path.relative_to(f.audio_path.parent.parent.parent)
        clips.append(
            {
                "id": f.clip_id,
                "title_en": meta.get("title_en", f.clip_id),
                "title_es": meta.get("title_es", f.clip_id),
                "category": f.category,
                "duration_seconds": round(f.duration_seconds, 3),
                "sample_rate": f.sample_rate,
                "audio_path": str(rel_audio).replace("\\", "/"),
                "embedding_path": f"embeddings/{f.clip_id}.json",
                "source": meta.get("source", ""),
                "license": meta.get("license", ""),
                "attribution": meta.get("attribution", ""),
                "tags": meta.get("tags", []),
            }
        )

    payload = {
        "version": VERSION,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "feature_names": list(SCALAR_FEATURES),
        "embedding_methods": method_names,
        "categories": categories_in_use,
        "clips": clips,
    }
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    with MANIFEST_PATH.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    return MANIFEST_PATH
